### ISSUE TITLE
Ability to hide default save directory in context menu

### ISSUE THREAD

**Issue by pointydev** [userXinos/image-tools#8]
Hey there,

I think it'd be a cool idea to allow the user to hide the default save directory in context menus via a plugin setting, as it makes for quite a large menu. Currently I'm working around this with CSS, but it'd be great to see a proper setting for it.

Example:
![](https://the.uwu.foundation/2zcXoY5.png)
```css
/* Workaround */
#image-context-item-0-1-5 >div>div,
[id*="image-tools-button"][id$="-5"] >div>div {
  display: none;
}
```

Thanks,
Pointy
